#!/usr/bin/env python3
"""
13F Summary script
- Timeframe: user-specified (defaults here set to 2026-01-01 .. 2026-03-09)
- Finds 13F-HR filings in EDGAR QTR1 2026 master index, downloads filings,
  parses INFORMATION TABLE XML, and computes:
    * Top 50 filers by reported 13F assets (sum of reported values in latest filing)
    * Top 10 holdings by aggregated latest market value across selected filers
    * Top 10 buys (largest positive net dollar change) aggregated across filers
    * Top 10 sells (largest negative net dollar change) aggregated across filers
- Excludes ETFs (basic filter on name/title containing "ETF" or "Exchange Traded Fund")
- Applies minimum-change filter of $1,000,000 (configurable)
- Outputs console tables and CSV files.

Notes:
- SEC requires a descriptive User-Agent header including contact info when scraping. Edit USER_AGENT below.
- Run in an environment with internet access and Python 3.9+.
- Dependencies: requests, lxml, pandas, python-dateutil
    pip install requests lxml pandas python-dateutil
- Save as 13f_summary.py and run: python 13f_summary.py
-   or pass a local SEC DERA zip for the current quarter:
      python 13f_summary.py --zip /path/to/current_quarter_form13f.zip
-   pass BOTH a prior-quarter and current-quarter zip for buy/sell comparison:
      python 13f_summary.py --prior-zip /path/to/q3_form13f.zip \
                             --zip       /path/to/q4_form13f.zip
-   sample fixtures for dev/testing (single-zip mode, two filings per filer):
      python 13f_summary.py --zip fixtures/sample_13f.zip
-   sample fixtures for dev/testing (two-zip mode, one filing per filer each):
      python 13f_summary.py --prior-zip fixtures/sample_13f_prior.zip \
                             --zip       fixtures/sample_13f_current.zip

About SEC DERA quarterly zips:
  Each quarterly zip contains ONE filing per filer.  A single zip therefore
  cannot compute buys/sells (net change = 0 for every security).  Provide
  the previous quarter's zip via --prior-zip to enable buy/sell comparison.
  Download quarterly zips from: https://www.sec.gov/dera/data/form-13f-data-sets

Author: generated by assistant (adapt as needed)
"""

import re
import csv
import io
import sys
import time
import math
import json
import gzip
import shutil
import logging
import zipfile
import argparse
import requests
import datetime as dt
import pandas as pd
from dateutil import parser as dateparse
from lxml import etree
from collections import defaultdict, Counter

# ---- CONFIG ----
USER_AGENT = "nicksirip-13f-summary-script/1.0 (youremail@example.com)"  # EDIT this to include a real contact per SEC policy
START_DATE = dt.date(2026, 1, 1)
END_DATE = dt.date(2026, 3, 9)
QTR_MASTER_URL_TEMPLATE = "https://www.sec.gov/Archives/edgar/full-index/{year}/QTR{qtr}/master.idx"
# We only need QTR1 2026 for the date range specified; script supports scanning multiple quarters if needed.
MIN_CHANGE_USD = 1_000_000  # $1M threshold as requested
TOP_FILERS_N = 50
INCLUDE_ETFS = False  # user requested exclude ETFs
OUTPUT_PREFIX = "13f_summary_2026-Q1_2026-01-01_to_2026-03-09"
LOCAL_ZIP_PATH = None  # Set to a local path of a SEC EDGAR 13F dataset zip to skip live downloads
                       # Download from: https://www.sec.gov/dera/data/form-13f-data-sets

# ---- END CONFIG ----

HEADERS = {"User-Agent": USER_AGENT, "Accept-Encoding": "gzip, deflate", "Host": "www.sec.gov"}

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

def fetch_master_index(year, qtr):
    url = QTR_MASTER_URL_TEMPLATE.format(year=year, qtr=qtr)
    logging.info("Downloading master index: %s", url)
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    content = r.text
    return content

def parse_master_idx_for_13f(master_idx_text, start_date, end_date):
    """
    Parse master.idx text and return list of tuples:
    (cik, company_name, form_type, date_filed (date), filename)
    Filtering for form_type == '13F-HR' and date range inclusive.
    """
    lines = master_idx_text.splitlines()
    # Find header line index where actual rows start (master.idx has a header of 10-ish lines)
    start_i = 0
    for i, ln in enumerate(lines[:40]):
        if ln.strip().startswith("CIK|Company Name|Form Type|Date Filed|Filename"):
            start_i = i + 1
            break
    rows = []
    for ln in lines[start_i:]:
        if not ln.strip():
            continue
        parts = ln.split('|')
        if len(parts) < 5:
            continue
        cik, company_name, form_type, date_filed_str, filename = parts[:5]
        try:
            date_filed = dateparse.parse(date_filed_str).date()
        except Exception:
            continue
        if form_type.strip().upper() != "13F-HR":
            continue
        if not (start_date <= date_filed <= end_date):
            continue
        rows.append({
            "cik": cik.strip(),
            "company_name": company_name.strip(),
            "form_type": form_type.strip(),
            "date_filed": date_filed,
            "filename": filename.strip()
        })
    logging.info("Found %d 13F-HR filings in master index within date range", len(rows))
    return rows

def fetch_filing_txt(filename):
    base = "https://www.sec.gov/Archives/"
    url = base + filename
    logging.info("Fetching filing text: %s", url)
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.text

def locate_information_table_xml_from_text(filing_text, filename_hint=None):
    """
    Attempt to extract the INFORMATION TABLE XML from the filing .txt.
    Approaches:
      1) If the .txt contains a direct <XML> ... </XML> or <informationTable> block, extract it.
      2) Otherwise, look for filenames in the filing that end with .xml and fetch them (caller must construct full URL).
    Returns tuple (xml_string, xml_filename_relative_or_none)
    """
    # 1) try to find <informationTable> block
    m = re.search(r'(<informationTable[\s\S]*?</informationTable>)', filing_text, flags=re.IGNORECASE)
    if m:
        logging.debug("Found informationTable block in main text")
        return m.group(1), None
    # Sometimes the infotable is inside <XML> ... </XML>
    m2 = re.search(r'(<\?xml[\s\S]*?</informationTable>)', filing_text, flags=re.IGNORECASE)
    if m2:
        logging.debug("Found XML block starting with <?xml")
        return m2.group(1), None
    # If not present, look for referenced xml filenames in the filing index listing
    # e.g., 'edgar/data/CIK/ACCESSION/infotable.xml' or filenames with 'xml'
    xml_files = re.findall(r'([^\s,"]+\.xml)', filing_text, flags=re.IGNORECASE)
    xml_files = [x for x in xml_files if 'infotable' in x.lower() or x.lower().endswith('.xml')]
    if xml_files:
        # return the first candidate filename string (caller should fetch using base + filename)
        logging.debug("Found referenced xml filename in filing: %s", xml_files[0])
        return None, xml_files[0]
    return None, None

def fetch_xml_by_path(xml_path):
    base = "https://www.sec.gov/Archives/"
    url = xml_path if xml_path.startswith("http") else base + xml_path
    logging.info("Fetching XML at: %s", url)
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.text

def parse_information_table_xml(xml_text):
    """
    Parse the informationTable / infoTable XML for holdings.
    Returns list of dictionaries per holding:
      {
        nameOfIssuer, titleOfClass, cusip, value (int, USD), shrsOrPrnAmt (int shares),
        sshPrnamt (float if fractional), putCall (optional)
      }
    Note: 13F values are typically reported in thousands of USD; some filings specify units. This script assumes reported 'value' in the XML is in thousands USD (we convert to USD).
    """
    # Ensure we can parse even if multiple roots present: attempt to wrap if needed
    try:
        parser = etree.XMLParser(recover=True)
        root = etree.fromstring(xml_text.encode('utf-8'), parser=parser)
    except Exception as e:
        # Try wrapping in a root
        try:
            wrapped = f"<root>{xml_text}</root>"
            root = etree.fromstring(wrapped.encode('utf-8'), parser=etree.XMLParser(recover=True))
        except Exception as e2:
            logging.error("XML parsing failed: %s", e2)
            return []

    # Find all infoTable elements (names differ by filing, use XPath ignoring namespace)
    info_tables = root.findall(".//{*}infoTable") or root.findall(".//infoTable") or root.findall(".//{*}informationTable")
    holdings = []
    # If infoTable not found, try to find elements named 'infotable' lower-case etc.
    if not info_tables:
        # brute force: any element named 'infoTable' or 'infotable' ignoring case
        for elem in root.iter():
            if elem.tag.lower().endswith('infotable'):
                info_tables.append(elem)
    for info in info_tables:
        try:
            # helper to find element text ignoring namespaces
            def find_text(parent, tag_name):
                el = parent.find(".//{*}" + tag_name)
                if el is None:
                    # try direct child with that localname
                    for ch in parent:
                        if ch.tag.lower().endswith(tag_name.lower()):
                            return (ch.text or "").strip()
                    return ""
                return (el.text or "").strip()
            name = find_text(info, "nameOfIssuer") or find_text(info, "nameofIssuer")
            title = find_text(info, "titleOfClass")
            cusip = find_text(info, "cusip")
            value_str = find_text(info, "value")
            # value reported in 13F is typically integer (in thousands of USD)
            value = 0
            try:
                value = int(re.sub(r'[^\\d\-]', '', value_str)) * 1000  # convert thousands -> USD
            except:
                try:
                    value = int(float(value_str) * 1000)
                except:
                    value = 0
            # shares
            shrs_el = info.find(".//{*}shrsOrPrnAmt")
            shares = None
            if shrs_el is not None:
                # find the amount subelement
                amount = None
                for ch in shrs_el:
                    if ch.tag.lower().endswith("sshPrnamt") or ch.tag.lower().endswith("sshPrnAmt".lower()):
                        amount = ch.text
                    if ch.tag.lower().endswith("sshPrnamt") or ch.tag.lower().endswith("sshPrnAmt"):
                        amount = ch.text
                # fallback: first numeric child
                if amount is None:
                    for ch in shrs_el:
                        if ch.text and re.search(r'\d', ch.text):
                            amount = ch.text
                            break
                if amount:
                    try:
                        shares = float(re.sub(r'[^\\d\.\-]', '', amount))
                    except:
                        shares = None
            holdings.append({
                "name": name,
                "title": title,
                "cusip": cusip,
                "value": value,
                "shares": shares
            })
        except Exception as ex:
            logging.exception("Failed parsing infoTable entry: %s", ex)
    return holdings

def is_etf(holding):
    name = (holding.get("name") or "").lower()
    title = (holding.get("title") or "").lower()
    if "exchange traded fund" in name or "exchange traded fund" in title:
        return True
    if "etf" in name.split() or "etf" in title.split():
        return True
    # heuristic: exclude tickers ending with .ETF etc (not reliable)
    return False

def aggregate_holdings_by_security(holdings_list):
    """
    holdings_list: list of dicts with keys name, cusip, value, shares
    Returns aggregated dict keyed by (cusip or name) with total value and total shares
    """
    agg = {}
    for h in holdings_list:
        key = h.get("cusip") or h.get("name")
        if not key:
            continue
        if key not in agg:
            agg[key] = {"name": h.get("name"), "cusip": h.get("cusip"), "value": 0, "shares": 0.0}
        try:
            agg[key]["value"] += int(h.get("value") or 0)
        except:
            pass
        try:
            if h.get("shares") is not None:
                agg[key]["shares"] += float(h.get("shares"))
        except:
            pass
    return agg

def load_holdings_from_zip(zip_path, start_date=None, end_date=None):
    """
    Load 13F holdings from a SEC EDGAR 13F dataset zip file.

    The SEC DERA quarterly 13F zips (https://www.sec.gov/dera/data/form-13f-data-sets)
    contain at minimum:
      - SUBMISSION.tsv  – filing metadata
          Columns: ACCESSION_NUMBER, FILING_DATE (DD-MON-YYYY), SUBMISSIONTYPE,
                   CIK, PERIODOFREPORT
          Note: company name is NOT in SUBMISSION; it lives in COVERPAGE.
      - INFOTABLE.tsv   – per-holding rows
          Columns: ACCESSION_NUMBER, INFOTABLE_SK, NAMEOFISSUER, TITLEOFCLASS,
                   CUSIP, VALUE (dollars since Jan 2023), SSHPRNAMT, SSHPRNAMTTYPE, …

    Parameters
    ----------
    zip_path : str | Path
        Local path to the DERA quarterly zip.
    start_date : datetime.date or None
        Only include filings on or after this date.  Pass None to include all.
    end_date : datetime.date or None
        Only include filings on or before this date.  Pass None to include all.

    Returns a filer_holdings defaultdict(list) in the same format used by the HTTP-based path:
      { "cik": [{"date": date, "holdings": [{"name":…, "title":…,
                                "cusip":…, "value":…, "shares":…}]}, …] }
    Note: when company name is absent from SUBMISSION (the real-world case per spec),
    filer keys are plain CIK strings so they match correctly across zips from different
    quarters.
    """
    logging.info("Loading 13F data from local zip: %s", zip_path)
    with zipfile.ZipFile(zip_path, "r") as zf:
        names = zf.namelist()
        sub_file = next((n for n in names if n.upper().endswith("SUBMISSION.TSV")), None)
        info_file = next((n for n in names if n.upper().endswith("INFOTABLE.TSV")), None)
        if sub_file is None:
            raise FileNotFoundError(
                f"SUBMISSION.tsv not found in zip. Files present: {names}"
            )
        if info_file is None:
            raise FileNotFoundError(
                f"INFOTABLE.tsv not found in zip. Files present: {names}"
            )
        logging.info("Reading %s", sub_file)
        with zf.open(sub_file) as f:
            sub_df = pd.read_csv(f, sep="\t", dtype=str, low_memory=False)
        logging.info("Reading %s", info_file)
        with zf.open(info_file) as f:
            info_df = pd.read_csv(f, sep="\t", dtype=str, low_memory=False)

    # Normalise column names to upper-case and strip BOM (UTF-8 BOM \ufeff can
    # prefix the first column name in government-generated TSV files)
    sub_df.columns = [c.strip().lstrip('\ufeff').upper() for c in sub_df.columns]
    info_df.columns = [c.strip().lstrip('\ufeff').upper() for c in info_df.columns]
    logging.info("SUBMISSION columns: %s", list(sub_df.columns))
    logging.info("INFOTABLE columns:  %s", list(info_df.columns))

    # Locate key columns in SUBMISSION (names vary slightly across dataset vintages)
    def _find_col(df, candidates):
        for c in candidates:
            if c in df.columns:
                return c
        raise KeyError(
            f"None of {candidates} found in columns: {list(df.columns)}"
        )

    # FILING_DATE is the current spec name; older vintages used FILED / FILEDATE
    date_col     = _find_col(sub_df, ["FILING_DATE", "FILED", "FILED_DATE", "FILEDATE"])
    # SUBMISSIONTYPE is the current spec name; older vintages used FORM_TYPE / FORMTYPE
    form_col     = _find_col(sub_df, ["SUBMISSIONTYPE", "FORM_TYPE", "FORMTYPE", "TYPE"])
    cik_col      = _find_col(sub_df, ["CIK", "CIK_NO", "CIKNUMBER"])
    acc_col_sub  = _find_col(sub_df, ["ACCESSION_NUMBER", "ACCESSION_NO", "ACCESSIONNO"])

    # Company name is in COVERPAGE (not SUBMISSION) per the SEC DERA spec.
    # Accept it if present for convenience; fall back to CIK-only filer key.
    try:
        name_col = _find_col(sub_df, ["COMPANYNAME", "COMPANY_NAME", "CONFORMED_NAME",
                                      "ENTITY_NAME", "FILINGMANAGER_NAME"])
    except KeyError:
        name_col = None
        logging.info(
            "No company-name column found in SUBMISSION (expected — per spec, "
            "company name lives in COVERPAGE). Filer keys will use CIK only."
        )

    # Locate key columns in INFOTABLE
    acc_col_info = _find_col(info_df, ["ACCESSION_NUMBER", "ACCESSION_NO", "ACCESSIONNO"])
    issuer_col   = _find_col(info_df, ["NAMEOFISSUER", "NAME_OF_ISSUER"])
    title_col    = _find_col(info_df, ["TITLEOFCLASS", "TITLE_OF_CLASS"])
    cusip_col    = _find_col(info_df, ["CUSIP"])
    value_col    = _find_col(info_df, ["VALUE"])
    shares_col   = _find_col(info_df, ["SSHPRNAMT", "SSH_PRNAMT"])

    # Filter SUBMISSION to 13F-HR filings, optionally within a date range.
    # Compare as Timestamps (avoids NaT vs datetime.date TypeError in some pandas versions).
    # The spec uses DD-MON-YYYY (e.g. "15-JAN-2026"). format="mixed" tells pandas to
    # parse each value individually via dateutil without emitting an inference warning.
    try:
        sub_df[date_col] = pd.to_datetime(
            sub_df[date_col], format="mixed", dayfirst=True, errors="coerce"
        )
    except TypeError:
        # pandas < 2.0 does not support format="mixed"; fall back gracefully
        sub_df[date_col] = pd.to_datetime(sub_df[date_col], infer_datetime_format=True, errors="coerce")

    mask = sub_df[form_col].str.strip().str.upper() == "13F-HR"
    if start_date is not None:
        mask = mask & (sub_df[date_col] >= pd.Timestamp(start_date))
    if end_date is not None:
        mask = mask & (sub_df[date_col] <= pd.Timestamp(end_date))

    filtered_sub = sub_df[mask].copy()
    logging.info(
        "Found %d 13F-HR filings in zip%s",
        len(filtered_sub),
        f" within date range {start_date} to {end_date}" if (start_date or end_date) else "",
    )
    if filtered_sub.empty:
        return defaultdict(list)

    # Restrict INFOTABLE to only the matching accession numbers, then pre-group
    # by accession so each lookup is O(1) instead of a full-table scan per filing.
    valid_accessions = set(filtered_sub[acc_col_sub].dropna().unique())
    info_filtered = info_df[info_df[acc_col_info].isin(valid_accessions)].copy()
    info_by_accession = {
        acc: grp for acc, grp in info_filtered.groupby(acc_col_info, sort=False)
    }
    logging.info(
        "INFOTABLE filtered to %d rows across %d accessions",
        len(info_filtered), len(info_by_accession),
    )

    # Build filer_holdings in the same shape as the HTTP-based path
    filer_holdings = defaultdict(list)
    for _, row in filtered_sub.iterrows():
        accession  = row[acc_col_sub]
        cik        = str(row.get(cik_col, "") or "").strip()
        company    = str(row.get(name_col, "") or "").strip() if name_col else ""
        filed_date = row[date_col].date()
        filer_key  = f"{cik}|{company}" if company else cik

        holding_rows = info_by_accession.get(accession)
        if holding_rows is None or holding_rows.empty:
            filer_holdings[filer_key].append({"date": filed_date, "holdings": []})
            continue

        holdings = []
        for _, hr in holding_rows.iterrows():
            try:
                value_str = str(hr.get(value_col, "0") or "0").strip()
                try:
                    # Since January 2023 SEC reports VALUE in dollars (not thousands).
                    value = int(re.sub(r"[^\d\-]", "", value_str))
                except Exception:
                    try:
                        value = int(float(value_str))
                    except Exception:
                        value = 0
                shares_str = str(hr.get(shares_col, "") or "").strip()
                shares = None
                if shares_str:
                    try:
                        shares = float(re.sub(r"[^\d\.\-]", "", shares_str))
                    except Exception:
                        shares = None
                holdings.append({
                    "name":  str(hr.get(issuer_col, "") or "").strip(),
                    "title": str(hr.get(title_col,  "") or "").strip(),
                    "cusip": str(hr.get(cusip_col,  "") or "").strip(),
                    "value": value,
                    "shares": shares,
                })
            except Exception as ex:
                logging.warning("Skipping INFOTABLE row: %s", ex)
        filer_holdings[filer_key].append({"date": filed_date, "holdings": holdings})

    return filer_holdings


def main():
    parser = argparse.ArgumentParser(
        description="Summarise 13F filings from SEC EDGAR.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # live download from EDGAR (needs internet)\n"
            "  python 13f_summary.py\n\n"
            "  # single quarterly zip (top holdings only; no buy/sell — one filing per filer)\n"
            "  python 13f_summary.py --zip /Downloads/q4_form13f.zip\n\n"
            "  # two consecutive quarterly zips → enables buy/sell comparison\n"
            "  python 13f_summary.py --prior-zip /Downloads/q3_form13f.zip \\\n"
            "                         --zip       /Downloads/q4_form13f.zip\n\n"
            "  # sample fixtures for development / CI (single-zip, two dates in one file)\n"
            "  python 13f_summary.py --zip fixtures/sample_13f.zip\n\n"
            "  # sample fixtures for development / CI (two-zip mode)\n"
            "  python 13f_summary.py --prior-zip fixtures/sample_13f_prior.zip \\\n"
            "                         --zip       fixtures/sample_13f_current.zip\n"
        ),
    )
    parser.add_argument(
        "--zip", "-z",
        metavar="PATH",
        default=None,
        help=(
            "Path to the current-quarter SEC DERA 13F dataset zip file. "
            "Each quarterly zip contains one filing per filer; combine with "
            "--prior-zip to compute buy/sell changes across quarters. "
            "Download from https://www.sec.gov/dera/data/form-13f-data-sets"
        ),
    )
    parser.add_argument(
        "--prior-zip", "-p",
        metavar="PATH",
        default=None,
        help=(
            "Path to the PRIOR quarter's SEC DERA 13F dataset zip file. "
            "When provided together with --zip the script computes net changes "
            "(buys / sells) by comparing holdings across the two quarters."
        ),
    )
    parser.add_argument(
        "--top-n", "-n",
        metavar="N",
        type=int,
        default=10,
        help=(
            "Number of top holdings, buys, and sells to display and save to CSV. "
            "Defaults to 10."
        ),
    )
    args = parser.parse_args()

    # CLI flags take precedence over the in-file config constant
    zip_path       = args.zip or LOCAL_ZIP_PATH
    prior_zip_path = args.prior_zip
    top_n          = args.top_n

    logging.info("Starting 13F summary process")

    if zip_path:
        if prior_zip_path:
            # ---------------------------------------------------------------
            # Two-zip mode: compare prior quarter vs current quarter.
            # Load each zip without a date filter (take ALL 13F-HR rows).
            # Holdings from the prior zip become the "earliest" snapshot;
            # holdings from the current zip become the "latest" snapshot.
            # Filer keys are plain CIKs (no company name in SUBMISSION) so
            # they match correctly across quarters.
            # ---------------------------------------------------------------
            logging.info("Two-zip mode: comparing %s (prior) vs %s (current)",
                         prior_zip_path, zip_path)
            prior_holdings   = load_holdings_from_zip(prior_zip_path)
            current_holdings = load_holdings_from_zip(zip_path)

            if not current_holdings:
                logging.error("No 13F-HR filings found in current-quarter zip")
                sys.exit(1)
            if not prior_holdings:
                logging.warning(
                    "No 13F-HR filings found in prior-quarter zip; "
                    "buy/sell changes will not be computed."
                )

            # Merge into a single filer_holdings dict.  Each filer will end up
            # with two entries (one per zip) which the existing earliest/latest
            # logic will then compare.
            filer_holdings = defaultdict(list)
            for filer_key, entries in current_holdings.items():
                filer_holdings[filer_key].extend(entries)
            for filer_key, entries in prior_holdings.items():
                filer_holdings[filer_key].extend(entries)
        else:
            # ---------------------------------------------------------------
            # Single-zip mode (backward compatible).
            # Useful when the zip itself contains multiple filings per filer
            # (e.g. the sample fixture, or a multi-period export).
            # Date-range filter keeps only filings within START_DATE..END_DATE.
            # ---------------------------------------------------------------
            logging.info(
                "Single-zip mode: loading from %s (date range %s to %s). "
                "TIP: use --prior-zip to compare against a prior quarter for buy/sell data.",
                zip_path, START_DATE, END_DATE,
            )
            filer_holdings = load_holdings_from_zip(zip_path, START_DATE, END_DATE)
            if not filer_holdings:
                logging.error("No 13F-HR filings found in zip for the date range")
                sys.exit(1)
    else:
        # For timeframe given, determine relevant quarters (simple approach: Q1 2026)
        year = 2026
        qtr = 1
        master_text = fetch_master_index(year, qtr)
        filings = parse_master_idx_for_13f(master_text, START_DATE, END_DATE)
        if not filings:
            logging.error("No 13F-HR filings found in the master index for the date range")
            sys.exit(1)

        # For each filing, fetch filing text, locate informationTable XML, fetch/parse holdings
        # We'll keep per-filer a list of (date_filed, holdings_list)
        filer_holdings = defaultdict(list)  # key: (cik|company_name) -> list of dicts {date, holdings}
        for f in filings:
            try:
                txt = fetch_filing_txt(f["filename"])
                xml_block, xml_filename = locate_information_table_xml_from_text(txt, filename_hint=f["filename"])
                xml_text = None
                if xml_block:
                    xml_text = xml_block
                elif xml_filename:
                    # xml_filename might be a relative path or full path; construct full path when relative
                    # Some filenames in master.idx are relative to /Archives/ so prefix is handled
                    if xml_filename.startswith("http"):
                        xml_path = xml_filename
                    else:
                        # If xml_filename appears incomplete (for example just the file name), try to construct path using filing's directory
                        # Extract directory from f["filename"]
                        dirpath = "/".join(f["filename"].split("/")[:-1]) + "/"
                        xml_path = dirpath + xml_filename
                    xml_text = fetch_xml_by_path(xml_path)
                else:
                    logging.warning("Could not find XML informationTable for filing: %s %s", f["company_name"], f["filename"])
                    continue
                holdings = parse_information_table_xml(xml_text)
                filer_key = f"{f['cik']}|{f['company_name']}"
                filer_holdings[filer_key].append({"date": f["date_filed"], "holdings": holdings})
                # polite pause to avoid hammering SEC
                time.sleep(0.2)
            except Exception as e:
                logging.exception("Error processing filing %s: %s", f.get("filename"), e)

    # For each filer, we need earliest and latest filing within the timeframe to compute net change.
    # We'll also compute latest total assets (sum of value) for ranking top filers.
    filer_summaries = {}
    for filer, entries in filer_holdings.items():
        if not entries:
            continue
        # sort entries by date
        entries_sorted = sorted(entries, key=lambda x: x["date"])
        earliest = entries_sorted[0]
        latest = entries_sorted[-1]
        # aggregate holdings to dict keyed by cusip/name
        earliest_agg = aggregate_holdings_by_security(earliest["holdings"])
        latest_agg = aggregate_holdings_by_security(latest["holdings"])
        # compute total assets (sum of latest values)
        total_assets = sum([v["value"] for v in latest_agg.values()])
        filer_summaries[filer] = {
            "earliest_date": earliest["date"],
            "latest_date": latest["date"],
            "earliest_agg": earliest_agg,
            "latest_agg": latest_agg,
            "total_assets": total_assets
        }

    if not filer_summaries:
        logging.error("No filer summaries produced; aborting")
        sys.exit(1)

    # Select top N filers by total_assets
    sorted_filers = sorted(filer_summaries.items(), key=lambda x: x[1]["total_assets"], reverse=True)
    top_filers = sorted_filers[:TOP_FILERS_N]
    logging.info("Selected top %d filers by reported assets (within timeframe)", len(top_filers))

    # Now aggregate across the selected filers:
    # For each security key (cusip or name), sum latest value across filers and sum net change = latest_value - earliest_value
    aggregated = {}
    for filer, summary in top_filers:
        latest = summary["latest_agg"]
        earliest = summary["earliest_agg"]
        for key, lv in latest.items():
            # basic ETF exclusion
            if (not INCLUDE_ETFS) and is_etf(lv):
                continue
            en = earliest.get(key)
            ev = en["value"] if en is not None else 0
            net_change = lv["value"] - ev
            if key not in aggregated:
                aggregated[key] = {
                    "name": lv.get("name"),
                    "cusip": lv.get("cusip"),
                    "latest_value": 0,
                    "latest_shares": 0.0,
                    "net_change": 0
                }
            aggregated[key]["latest_value"] += lv.get("value", 0)
            try:
                aggregated[key]["latest_shares"] += lv.get("shares") or 0.0
            except:
                pass
            aggregated[key]["net_change"] += net_change

        # Also capture securities present only in earliest (i.e., closed positions) to ensure sells are recorded
        for key, ev_item in earliest.items():
            if key in latest:
                continue
            # security was present earlier but not in latest -> latest_value = 0, net_change = 0 - ev
            if (not INCLUDE_ETFS) and is_etf(ev_item):
                continue
            if key not in aggregated:
                aggregated[key] = {
                    "name": ev_item.get("name"),
                    "cusip": ev_item.get("cusip"),
                    "latest_value": 0,
                    "latest_shares": 0.0,
                    "net_change": 0
                }
            aggregated[key]["net_change"] += (0 - ev_item.get("value", 0))

    # Convert aggregated to DataFrame
    rows = []
    for key, v in aggregated.items():
        rows.append({
            "key": key,
            "name": v.get("name"),
            "cusip": v.get("cusip"),
            "latest_value_usd": v.get("latest_value", 0),
            "latest_shares": v.get("latest_shares", 0.0),
            "net_change_usd": v.get("net_change", 0)
        })
    df = pd.DataFrame(rows)
    if df.empty:
        logging.error("Aggregated DataFrame is empty; no securities after filtering")
        sys.exit(1)

    # Apply $1M filter on net change when selecting buys/sells
    df_buys = df[df["net_change_usd"] >= MIN_CHANGE_USD].sort_values("net_change_usd", ascending=False)
    df_sells = df[df["net_change_usd"] <= -MIN_CHANGE_USD].sort_values("net_change_usd")
    df_top_holdings = df.sort_values("latest_value_usd", ascending=False)

    # Top N holdings / buys / sells
    top_n_holdings = df_top_holdings.head(top_n).copy()
    top_n_buys     = df_buys.head(top_n).copy()
    top_n_sells    = df_sells.head(top_n).copy()

    # Print chat-friendly tables
    def usd(x):
        try:
            return "${:,.0f}".format(float(x))
        except:
            return x

    print(f"\nTop {top_n} holdings (aggregated latest market value across top filers):")
    if top_n_holdings.empty:
        print("  (no holdings found)")
    else:
        print(top_n_holdings[["name", "cusip", "latest_value_usd"]].to_string(index=False, formatters={"latest_value_usd": usd}))

    print(f"\nTop {top_n} buys by dollar volume (net change >= ${MIN_CHANGE_USD:,}):")
    if top_n_buys.empty:
        print("  (no buys above threshold)")
    else:
        print(top_n_buys[["name", "cusip", "net_change_usd", "latest_value_usd"]].to_string(index=False, formatters={"net_change_usd": usd, "latest_value_usd": usd}))

    print(f"\nTop {top_n} sells by dollar volume (net change <= -${MIN_CHANGE_USD:,}):")
    if top_n_sells.empty:
        print("  (no sells above threshold)")
    else:
        print(top_n_sells[["name", "cusip", "net_change_usd", "latest_value_usd"]].to_string(index=False, formatters={"net_change_usd": usd, "latest_value_usd": usd}))

    # Save CSVs for later use
    top_n_holdings.to_csv(f"{OUTPUT_PREFIX}_top{top_n}_holdings.csv", index=False)
    top_n_buys.to_csv(f"{OUTPUT_PREFIX}_top{top_n}_buys.csv", index=False)
    top_n_sells.to_csv(f"{OUTPUT_PREFIX}_top{top_n}_sells.csv", index=False)
    df.to_csv(f"{OUTPUT_PREFIX}_all_aggregated.csv", index=False)
    logging.info("Saved CSV outputs with prefix: %s", OUTPUT_PREFIX)
    logging.info("Done.")

if __name__ == "__main__":
    main()